### ISSUE TITLE
EOFError

### ISSUE THREAD

**Issue by Jingyilang** [jarfo/gcommands#1]
It prints EOFError: sox data/speech_commands/train/audio/two/12c206ea_nohash_0.wav -t wav - trim 0 =1 | when I run this code. Could you give me some advices?

**Comment by jarfo** [comment]
Probably the file has not been copied correctly. You can check the file with 'ls -lh' or 'soxi', i.e.,
soxi data/speech_commands/train/audio/two/12c206ea_nohash_0.wav
